twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes:  ['bootstrap_4_layout.html.twig']

    globals:
        pageHeading: 'ITitle'
        sCountUnreadNews: ''
        sCountUnreadMessages: ''
        totalNewsCount: 0
        displayInTopListNewsCount: 0
        totalMessagesCount: 0
        displayInTopListMessagesCount: 0
        aNews: []
        aMessages: []